-- CREATE DATABASE/TABLES

CREATE DATABASE IF NOT EXISTS RateMyCoach;
USE RateMyCoach;

-- Division Table
CREATE TABLE Division (
    div_ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

-- Conference Table
CREATE TABLE Conference (
    con_ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    div_ID INT,
    FOREIGN KEY (div_ID) REFERENCES Division(div_ID)
);

-- Coach Table
CREATE TABLE Coach (
    coach_ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    team VARCHAR(100),
    con_ID INT,
    avg_rating DECIMAL(3,2) DEFAULT 0,
    FOREIGN KEY (con_ID) REFERENCES Conference(con_ID)
);

-- User Table
CREATE TABLE User (
    u_ID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    passw VARCHAR(255) NOT NULL,
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE User ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;


-- Review Table
CREATE TABLE Review (
    r_ID INT AUTO_INCREMENT PRIMARY KEY,
    u_ID INT NOT NULL,
    coach_ID INT NOT NULL,
    rating INT CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (u_ID) REFERENCES User(u_ID),
    FOREIGN KEY (coach_ID) REFERENCES Coach(coach_ID)
);

CREATE TABLE ReviewLog (
    log_ID INT AUTO_INCREMENT PRIMARY KEY,
    u_ID INT,
    coach_ID INT,
    action VARCHAR(50),
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (u_ID) REFERENCES User(u_ID),
    FOREIGN KEY (coach_ID) REFERENCES Coach(coach_ID)
);

ALTER TABLE Coach ADD FULLTEXT(name, team);




-- CREATE TRIGGERS --
DELIMITER //

CREATE TRIGGER update_avg_rating_after_review_insert
AFTER INSERT ON Review
FOR EACH ROW
BEGIN
    UPDATE Coach
    SET avg_rating = (
        SELECT COALESCE(AVG(rating), 0)
        FROM Review
        WHERE coach_ID = NEW.coach_ID AND is_deleted = FALSE
    )
    WHERE coach_ID = NEW.coach_ID;
END //

CREATE TRIGGER update_avg_rating_after_review_update
AFTER UPDATE ON Review
FOR EACH ROW
BEGIN
    UPDATE Coach
    SET avg_rating = (
        SELECT COALESCE(AVG(rating), 0)
        FROM Review
        WHERE coach_ID = NEW.coach_ID AND is_deleted = FALSE
    )
    WHERE coach_ID = NEW.coach_ID;
END //

CREATE TRIGGER update_avg_rating_after_review_delete
AFTER DELETE ON Review
FOR EACH ROW
BEGIN
    UPDATE Coach
    SET avg_rating = (
        SELECT COALESCE(AVG(rating), 0)
        FROM Review
        WHERE coach_ID = OLD.coach_ID AND is_deleted = FALSE
    )
    WHERE coach_ID = OLD.coach_ID;
END //

DELIMITER ;


-- INSERT SAMPLE DATA --

-- Divisions
INSERT INTO Division (name)
VALUES
    ('NCAA Division 1'),
    ('NCAA Division 2'),
    ('NCAA Division 3'),
    ('NAIA'),
    ('Junior College');

-- Conferences
INSERT INTO Conference (name, div_ID)
VALUES
    ('SQLAC', 1);

-- Coaches
INSERT INTO Coach (name, team, con_ID)
VALUES
    ('Rick Query', 'SQL university', 1),
    ('Jane Alias', 'University College', 1),
    ('Bob Bytes', 'Null State', 1);

-- Users
INSERT INTO User (username, email, passw)
VALUES
    ('user1', 'user1@example.com', 'pass');

-- Reviews
INSERT INTO Review (u_ID, coach_ID, rating, comment)
VALUES
    (1, 1, 5, 'Coach Ricky really knows how to develop pitchers.'),
    (1, 1, 4, 'Solid leadership, but tough on new players.'),
    (1, 3, 3, 'Decent coach, but struggles under pressure.'),
    (1, 3, 5, 'Coach Bytes brings energy to every game!'),
    (1, 3, 4, 'Great experience overall!');

INSERT INTO Conference (name, div_ID) VALUES
('Allegheny Mountain Collegiate Conference', 3),
('American Rivers Conference', 3),
('American Southwest Conference', 3),
('Atlantic East Conference', 3),
('Centennial Conference', 3),
('City University of New York Athletic Conference', 3),
('Coast-To-Coast Athletic Conference', 3),
('College Conference of Illinois & Wisconsin', 3),
('Collegiate Conference of the South', 3),
('Commonwealth Coast Conference', 3),
('Conference', 3),
('Empire 8', 3),
('Great Northeast Athletic Conference', 3),
('Heartland Collegiate Athletic Conference', 3),
('Landmark Conference', 3),
('Liberty League', 3),
('Little East Conference', 3),
('Massachusetts State Collegiate Athletic Conference', 3),
('Michigan Intercol. Ath. Assn.', 3),
('Middle Atlantic Conferences', 3),
('Midwest Conference', 3),
('Minnesota Intercollegiate Athletic Conference', 3),
('New England Small College Athletic Conference', 3),
('New England Women''s and Men''s Athletic Conference', 3),
('New Jersey Athletic Conference', 3),
('North Atlantic Conference', 3),
('North Coast Athletic Conference', 3),
('Northern Athletics Collegiate Conference', 3),
('Northwest Conference', 3),
('Ohio Athletic Conference', 3),
('Old Dominion Athletic Conf.', 3),
('Presidents'' Athletic Conference', 3),
('Skyline Conference', 3),
('Southern Athletic Association', 3),
('Southern California Intercollegiate Athletic Conf.', 3),
('Southern Collegiate Athletic Conference', 3),
('St. Louis Intercollegiate Athletic Conference', 3),
('State University of New York Athletic Conference', 3),
('The Summit League', 3),
('USA South Athletic Conference', 3),
('United East Conference', 3),
('University Athletic Association', 3),
('Upper Midwest Athletic Conference', 3);


INSERT INTO Coach (name, team, con_ID) VALUES
('Gunner Rainey ''21', 'Adrian College', 20),
('Aaron Klotz ''98', 'Adrian College', 20),
('Charlie Solis', 'Adrian College', 20),
('Matt Rix', 'Albion College', 20),
('Gary Yeager, Jr.', 'Albright College', 21),
('Patrick Causa', 'Albright College', 21),
('Thomas O''Driscoll', 'Albright College', 21),
('Nick Sklenarik', 'Albright College', 21),
('Mike Barry', 'Albright College', 21),
('Dale Murphy', 'Albright College', 21),
('Jake Kenney', 'Alfred State College', 2),
('Matteo Avallone', 'Alfred State College', 2),
('Bill Swanson', 'Alfred State College', 2),
('Marc Agnello', 'Alfred State College', 2),
('Brandon Higley', 'Alfred State College', 2),
('Tim Mack', 'Alfred State College', 2),
('Jake Kenney', 'Alfred University', 13),
('Matteo Avallone', 'Alfred University', 13),
('Bill Swanson', 'Alfred University', 13),
('Marc Agnello', 'Alfred University', 13),
('Brandon Higley', 'Alfred University', 13),
('Tim Mack', 'Alfred University', 13),
('Dave Veres', 'Alma College', 20),
('Brian Martin', 'Alma College', 20),
('Joe Yourchock', 'Alma College', 20),
('Chad Shade', 'Amherst College', 24),
('Kevin Murphy', 'Amherst College', 24),
('Brandon Schnepp', 'Anderson University (Indiana)', 15),
('Carlos Leyva', 'Anderson University (Indiana)', 15),
('Evan Doan', 'Anderson University (Indiana)', 15),
('Dylan Tice', 'Arcadia University', 21),
('Jimmy Gulden', 'Arcadia University', 21),
('Keith Curley', 'Arcadia University', 21),
('Jon Conant', 'Arcadia University', 21),
('Trey Obarowski ''23', 'Arcadia University', 21),
('Danny Bissonnette', 'Augsburg University', 23),
('Brock Peterson', 'Augsburg University', 23),
('Troy Deden', 'Augsburg University', 23),
('Jeff Stomberg', 'Augsburg University', 23),
('Bryan Ludwig', 'Augsburg University', 23),
('Kyle Nutting', 'Augsburg University', 23),
('Michael Jensen', 'Augsburg University', 23),
('Justin Hauer', 'Augustana College (Illinois)', 9),
('B.J. Eder', 'Augustana College (Illinois)', 9),
('Tyler Nunez', 'Augustana College (Illinois)', 9),
('Trenton Wallace', 'Augustana College (Illinois)', 9),
('Carter Turnquist', 'Aurora University', 29),
('Steve Moga', 'Aurora University', 29),
('Zack Skog', 'Aurora University', 29),
('Billy McLaughlin', 'Averett University', 32),
('Gavin Birkhimer', 'Averett University', 32),
('Tyler D. Smith', 'Averett University', 32),
('Matt Rosinski', 'Baldwin Wallace University', 31),
('Steve Hagen', 'Baldwin Wallace University', 31),
('Jake Smith ''20', 'Baldwin Wallace University', 31),
('Mark Terlep', 'Baldwin Wallace University', 31),
('Kevin McSweeney ''21', 'Baldwin Wallace University', 31),
('Daniel Carinci', 'Baldwin Wallace University', 31),
('Andrew Roberge ''22', 'Bard College', 17),
('Oswaldo Roman', 'Baruch College', 7),
('Mike Laflamme', 'Bates College', 24),
('Jeff Benson', 'Bates College', 24),
('Dale Plummer', 'Bates College', 24),
('Steven Ray Adams Jr.', 'Belhaven University', 10),
('Ed DeGeorge', 'Beloit College', 22),
('Mike Gulve', 'Beloit College', 22),
('Kerry Michaels', 'Beloit College', 22),
('Adam O''Malley', 'Benedictine University (Illinois)', 29),
('Jared Cantu', 'Benedictine University (Illinois)', 29),
('Kevin Sullivan', 'Benedictine University (Illinois)', 29),
('Dave Swanson', 'Benedictine University (Illinois)', 29),
('Cole Seltzer', 'Berea College', 10),
('Tyler Anderson', 'Berea College', 10),
('Justin Bramhall', 'Berea College', 10),
('Ben Coker', 'Berry College', 35),
('Dylan Beasley', 'Berry College', 35),
('Danny Kneeland', 'Bethany Lutheran College', 44),
('Logan Nissen', 'Bethany Lutheran College', 44),
('Ben Maes', 'Bethany Lutheran College', 44),
('Logan Gunther', 'Bethany Lutheran College', 44),
('Robb Gamm', 'Bethel University (Minnesota)', 23),
('Chad Richards', 'Bethel University (Minnesota)', 23),
('Paul Weidner', 'Bethel University (Minnesota)', 23),
('Ryan Meyers', 'Bethel University (Minnesota)', 23),
('Connor Malcolm', 'Bethel University (Minnesota)', 23),
('J.D. Hulse', 'Birmingham-Southern College', 35),
('Tristan Harvin', 'Birmingham-Southern College', 35),
('Zack Ingram', 'Birmingham-Southern College', 35),
('Rich Krueger', 'Blackburn College', 38),
('Brantley Curnutte', 'Bluffton University', 15),
('Brandon Wilson', 'Bluffton University', 15),
('Jason Jensen', 'Bowdoin College', 24),
('Austin Nicely', 'Bridgewater College (Virginia)', 32),
('Ryan Brewer', 'Bridgewater College (Virginia)', 32),
('Rick Reeves', 'Bridgewater College (Virginia)', 32),
('Vic Spotts', 'Bridgewater College (Virginia)', 32),
('Randy Frazier', 'Bridgewater State University', 19),
('Ken Lalli', 'Bridgewater State University', 19),
('Ian Searles', 'Bridgewater State University', 19),
('Patrick Sheehan', 'State University of New York at Brockport', 39),
('Jon Schwind', 'State University of New York at Brockport', 39),
('Kyle Canavally', 'State University of New York at Brockport', 39),
('Steve Eddie', 'Buena Vista University', 3),
('Nate Hanner', 'Buena Vista University', 3),
('Rod Johnson', 'Cabrini University', 5),
('Jesse James Murphy', 'Cabrini University', 5),
('Henry Peguero', 'Cabrini University', 5),
('Mack McKisson', 'Cabrini University', 5),
('Brendan Van Belle', 'Cabrini University', 5),
('Israel Cordero', 'Cabrini University', 5),
('Rob Barth', 'Cabrini University', 5),
('Brian Maglione', 'Cairn University', 42),
('Dom Maglione', 'Cairn University', 42),
('Victor Rivera', 'State University of New York at Canton', 27),
('Eddie Vargas', 'State University of New York at Canton', 27),
('Mike Paige', 'State University of New York at Canton', 27),
('Holden Martin', 'Capital University', 31),
('Ryan Henne', 'Capital University', 31),
('Jackson Wilson', 'Capital University', 31),
('Duke Dickerson', 'Capital University', 31),
('Steve Boyd', 'Capital University', 31),
('Emily Manahan', 'Capital University', 31),
('Bobby Zaayer', 'Capital University', 31),
('Kevin Flaherty', 'Capital University', 31),
('Dan Briggs', 'Capital University', 31),
('Brian Price', 'Carleton College', 23),
('Nate Van Roeckel', 'Carleton College', 23),
('Mike Michalak', 'Carleton College', 23),
('Alec Kotler', 'Carleton College', 23),
('Holden Martin', 'Carnegie Mellon University', 43),
('Ryan Henne', 'Carnegie Mellon University', 43),
('Jackson Wilson', 'Carnegie Mellon University', 43),
('Duke Dickerson', 'Carnegie Mellon University', 43),
('Steve Boyd', 'Carnegie Mellon University', 43),
('Emily Manahan', 'Carnegie Mellon University', 43),
('Bobby Zaayer', 'Carnegie Mellon University', 43),
('Kevin Flaherty', 'Carnegie Mellon University', 43),
('Dan Briggs', 'Carnegie Mellon University', 43),
('Jake Yellovich', 'Carroll University (Wisconsin)', 9),
('Dylan Callahan', 'Carroll University (Wisconsin)', 9),
('Jacob Nitch', 'Carroll University (Wisconsin)', 9),
('Brendan Charette', 'Carroll University (Wisconsin)', 9),
('Justin Baker', 'Carroll University (Wisconsin)', 9),
('Trevor Benz', 'Carroll University (Wisconsin)', 9),
('John Lequia', 'Carthage College', 9),
('John Hasser', 'Carthage College', 9),
('Joe Stevens', 'Carthage College', 9),
('Keith Kutzler', 'Carthage College', 9),
('Brian Budrow', 'Vermont State University Castleton', 18),
('Cody Crowder', 'Centenary College (Louisiana)', 37),
('Chris Zapata', 'Centenary College (Louisiana)', 37),
('Tyler Welch', 'Centenary College (Louisiana)', 37),
('Chris Miller', 'Centenary University (New Jersey)', 5),
('Angelo Rinaldi', 'Centenary University (New Jersey)', 5),
('Robby Laughlin', 'Central College (Iowa)', 3),
('Ian Boline', 'Central College (Iowa)', 3),
('Eric Van Wyngarden', 'Central College (Iowa)', 3),
('Taylor Valentine', 'Centre College', 35),
('Eric Deovlet', 'Chapman University', 36),
('Joe Torres', 'Chapman University', 36),
('Matt Lubaszewski', 'Christopher Newport University', 8),
('Steve Macias', 'The City College of New York', 7),
('Scott Losche', 'The City College of New York', 7),
('Christopher Jimenez', 'The City College of New York', 7),
('Nick Wagner', 'Claremont McKenna-Harvey Mudd-Scripps Colleges', 36),
('Quinn Heiner', 'Claremont McKenna-Harvey Mudd-Scripps Colleges', 36),
('David Higuera', 'Claremont McKenna-Harvey Mudd-Scripps Colleges', 36),
('Ryan Clark', 'Clarks Summit University', 42),
('Charlie Wright', 'Clarkson University', 17),
('Garrett Ferguson', 'Clarkson University', 17),
('Rob Frost', 'Clarkson University', 17),
('AJ Reuter', 'Coe College', 3),
('John Heald', 'Coe College', 3),
('Nolan Arp', 'Coe College', 3),
('Drew Schmit', 'Coe College', 3),
('Kevin DeLaney', 'Coe College', 3),
('Taylor Lockhart', 'Colby College', 24),
('Steve Lockard', 'Colby College', 24),
('Quinn Stebbins', 'Colby College', 24),
('Ken Walsh', 'Colby College', 24),
('Ryan Connolly ''08', 'Colby-Sawyer College', 14),
('Ryan Gill', 'Colby-Sawyer College', 14),
('Tim Moreau', 'Colby-Sawyer College', 14),
('Bucky Burgau', 'Concordia College, Moorhead', 23),
('Matt Smith', 'Concordia University Chicago', 29),
('Connor Nelson', 'Concordia University Chicago', 29),
('Jose Mercado', 'Concordia University Chicago', 29),
('Jake Garvey', 'Concordia University Chicago', 29),
('Garry Maynard', 'Concordia University Chicago', 29),
('Carlos Perez', 'Concordia University Texas', 4),
('Caleb Rodriguez', 'Concordia University Texas', 4),
('Jason Winkler', 'Concordia University Texas', 4),
('Craig Sini', 'Concordia University Texas', 4),
('Mark Keeney', 'Concordia University Texas', 4),
('Austin Gussman', 'Concordia University Wisconsin', 29),
('Frank Fishler', 'Cornell College', 22),
('Kevin Grant', 'Cornell College', 22),
('Josh Soper', 'Cornell College', 22),
('Cory Haggerty', 'State University of New York at Cortland', 39),
('Zack Durant', 'State University of New York at Cortland', 39),
('Aaron Spragg', 'Covenant College', 10),
('Josh Harvey', 'Covenant College', 10),
('Jake Kraft', 'Crown College (Minnesota)', 44),
('Jace Baumann', 'Crown College (Minnesota)', 44),
('Rusty Whittemore', 'Curry College', 11),
('Mike Bortolotti', 'Curry College', 11),
('Nick Faggas', 'Curry College', 11),
('Derek Pizzaro ''15', 'Curry College', 11),
('Ethan Harris', 'Dean College', 14),
('Joe Webber', 'Dean College', 14),
('Cole Holsinger', 'Delaware Valley University', 21),
('Kyle Bailey', 'Delaware Valley University', 21),
('Alex Crim', 'Delaware Valley University', 21),
('Tervont Johnson', 'State University of New York at Delhi', 27),
('Mike Deegan', 'Denison University', 28),
('Jon Erhard', 'DePauw University', 28),
('Pete Meyer', 'DePauw University', 28),
('Preston Amato', 'DeSales University', 21),
('JJ Paul', 'DeSales University', 21),
('Jake McGeary', 'DeSales University', 21),
('Pat Rhoads', 'DeSales University', 21),
('Brian Goodling', 'Dickinson College', 6),
('Steve Hardman', 'Dominican University (Illinois)', 29),
('Seth Dvorak', 'Dominican University (Illinois)', 29),
('Tyler Kara', 'Dominican University (Illinois)', 29),
('Jared Wojcik', 'Dominican University (Illinois)', 29),
('Jonathan Biale', 'Drew University', 16),
('Ross Halkias', 'Drew University', 16),
('Brad Hedden', 'Drew University', 16),
('Sean Buldiger', 'Drew University', 16),
('Anthony Goergen', 'Drew University', 16),
('Nick Pellegrino', 'Drew University', 16),
('Corey Hamman', 'Drew University', 16),
('Andrew Redman', 'University of Dubuque', 3),
('Jordan Goldstein', 'University of Dubuque', 3),
('Jake Fiorito', 'University of Dubuque', 3),
('Blake Peterson', 'Earlham College', 15),
('Dan Wilcher', 'Earlham College', 15),
('Kevin McGee', 'Earlham College', 15),
('Brandon Pennington', 'Earlham College', 15),
('Patrick Flanagan', 'Earlham College', 15),
('Devin Basley', 'Earlham College', 15),
('Austin Hatfield', 'Earlham College', 15),
('Darrin Lenhart', 'East Texas Baptist University', 4),
('Brandon Snyder', 'East Texas Baptist University', 4),
('Joe Baran', 'East Texas Baptist University', 4),
('Jake Packer', 'East Texas Baptist University', 4),
('Steve Cervizzi', 'Eastern Connecticut State University', 18),
('Len Reed', 'Eastern Connecticut State University', 18),
('Marc Senia', 'Eastern Connecticut State University', 18),
('Mike Grant', 'Eastern Connecticut State University', 18),
('Andy Baylock', 'Eastern Connecticut State University', 18),
('Nik Lassonde', 'Eastern Connecticut State University', 18),
('Kyle Friebolin', 'Eastern University', 21),
('Tucker McClure', 'Eastern University', 21),
('Joe Clancy', 'Eastern University', 21),
('Will Algard', 'Eastern University', 21),
('Matt Esquijerosa', 'Eastern University', 21),
('Tim Munz', 'Eastern University', 21),
('Max Orput', 'Edgewood College', 29),
('Ralph Kalal', 'Edgewood College', 29),
('Alex Prindle', 'Edgewood College', 29),
('Isaac Weinberg', 'Edgewood College', 29),
('Nick Holland', 'Edgewood College', 29),
('Cooper Holewinski', 'Edgewood College', 29),
('Eric Yoder', 'Elizabethtown College', 16),
('Jim Tetkoskie', 'Elizabethtown College', 16),
('Nolan Quinn', 'Elizabethtown College', 16),
('Eric Outlaw', 'Elmhurst University', 9),
('Cori Herbert', 'Elmhurst University', 9),
('Nick Heiden', 'Elmhurst University', 9),
('Rob Marinec', 'Elmhurst University', 9),
('Joe Marras', 'Elmhurst University', 9),
('Mark Ryan ''21', 'Elmira College', 13),
('Cameron Heggie ''18', 'Elmira College', 13),
('Jack Donnelly ''19', 'Elmira College', 13),
('Jared Money ''22', 'Elmira College', 13),
('Tony Dismukes', 'Elms College', 14),
('Phil Guidrey', 'Elms College', 14),
('Pedro Santiago', 'Elms College', 14),
('Kyle Cliff', 'Emory University', 43),
('Tyler Zunkel', 'Emory University', 43),
('John Kuczko', 'Emory University', 43),
('Alexander Loparco', 'Endicott College', 11),
('Frank DeFelice', 'Endicott College', 11),
('Steve Busby', 'Endicott College', 11),
('Patrick Tevenan ''23', 'Endicott College', 11),
('Ryan Bredeson', 'Eureka College', 38),
('Gino Mirabella', 'Fairleigh Dickinson University, Florham', 21),
('Jake Hall', 'Fairleigh Dickinson University, Florham', 21),
('Henry Warner', 'Fairleigh Dickinson University, Florham', 21),
('Bobby Shepard', 'Fairleigh Dickinson University, Florham', 21),
('AJ Yurista', 'Fairleigh Dickinson University, Florham', 21),
('Mike Dell''Unto', 'Fairleigh Dickinson University, Florham', 21),
('Mike McCabe', 'Farmingdale State College', 34),
('Anthony Zitaglio', 'Farmingdale State College', 34),
('Brett Kaminski', 'Ferrum College', 32),
('Chip Schaffner', 'Ferrum College', 32),
('Sam Dorner', 'Fontbonne University', 38),
('John Siener', 'Fontbonne University', 38),
('Nick Rothweiler', 'Fontbonne University', 38),
('Tyler Heitman', 'Fontbonne University', 38),
('Charlie LaDuca', 'The State University of New York at Fredonia', 39),
('Ryan Hann', 'The State University of New York at Fredonia', 39),
('Brandon Rupp', 'George Fox University', 30),
('Andrew Hunter', 'George Fox University', 30),
('Brian Pollard', 'George Fox University', 30),
('Carol Laube', 'George Fox University', 30),
('Trevor Nannini', 'George Fox University', 30),
('Jeremy Hefele', 'Gettysburg College', 6),
('Michael Festa', 'Gettysburg College', 6),
('Brooks Warrenfeltz', 'Gettysburg College', 6),
('Kyle Bouchard', 'Gordon College', 11),
('Connor Hartman', 'Gordon College', 11),
('Christian Dix', 'Greensboro College', 41),
('Bert Gonzalez', 'Greensboro College', 41),
('Nick DeTringo', 'Greensboro College', 41),
('Ryan Hutchinson', 'Greenville University', 38),
('Adam Kopff', 'Greenville University', 38),
('Phil Reedy', 'Greenville University', 38),
('Clarence Falls', 'Greenville University', 38),
('Sean Pfeiffer', 'Grinnell College', 22),
('Lucas Rollins', 'Gwynedd Mercy University', 5),
('Erik Carlson', 'Hamilton College', 24),
('Zach Crane', 'Hamilton College', 24),
('Aaron Rushing', 'Hamline University', 23),
('Cass Kreitlow', 'Hamline University', 23),
('Ryan Price', 'Hamline University', 23),
('Teague Bogenholm', 'Hamline University', 23),
('Nolan Schooneveld', 'Hamline University', 23),
('Robbie Bailey ''10', 'Hampden-Sydney College', 32),
('Billy Catron', 'Hampden-Sydney College', 32),
('Jonathan Triesler ''20', 'Hampden-Sydney College', 32),
('Drew Murray', 'Hanover College', 15),
('Cooper French', 'Hanover College', 15),
('Kase Lawson', 'Hanover College', 15),
('Brad Holcomb', 'Hardin-Simmons University', 4),
('Dave Beccaria', 'Haverford College', 6),
('Kevin Morgan', 'Haverford College', 6),
('Dan Crowley ''90', 'Haverford College', 6),
('Nicky Miranda ''14', 'Haverford College', 6),
('Chris Oakley', 'Haverford College', 6),
('William Bannard ''14', 'Haverford College', 6),
('Ben Somorjai ''21', 'Haverford College', 6),
('Ryan Giovenco ''21', 'Haverford College', 6),
('Jacob Terao', 'Hendrix College', 35),
('Ed Linck', 'Hendrix College', 35),
('Jacob Bruning', 'Hilbert College', 2),
('Brendan Toughey', 'Hilbert College', 2),
('Connor Priester', 'Hilbert College', 2),
('Ryan Nordquist', 'Hiram College', 28),
('Bob Merritt', 'Hiram College', 28),
('Michael Corsillo', 'Hiram College', 28),
('Vincent Redmond', 'Hobart and William Smith Colleges', 17),
('Lukas Olsson', 'Hobart and William Smith Colleges', 17),
('Dan Pontes', 'Hobart and William Smith Colleges', 17),
('Ellison Hanna II', 'Hood College', 21),
('Jordan Patterson', 'Hood College', 21),
('J.P. Soto', 'Hood College', 21),
('Evan Englebrook', 'Hood College', 21),
('Ryan Dorow', 'Hope College', 20),
('Devin Schaefers', 'Hope College', 20),
('Parker Friend', 'Hope College', 20),
('Keaton Hamilton', 'Hope College', 20),
('Tom Kenney', 'Houghton University', 13),
('Nick Pettit', 'Houghton University', 13),
('Tony Heiser', 'Howard Payne University', 4),
('Will Iannacone', 'Howard Payne University', 4),
('Matthew White', 'Illinois College', 22),
('Zach Hatton', 'Illinois College', 22),
('Logan Bledsaw', 'Illinois College', 22),
('Jayden Kasai', 'Illinois College', 22),
('Travis Mullins', 'Illinois College', 22),
('Michael Kellar', 'Illinois Wesleyan University', 9),
('Tim Siegworth', 'Illinois Wesleyan University', 9),
('Matt Willey', 'Illinois Wesleyan University', 9),
('Jeff Paglione', 'Immaculata University', 5),
('Tim Gunn', 'Immaculata University', 5),
('Dave Raifsnider', 'Immaculata University', 5),
('Cooper Belyea', 'Ithaca College', 17),
('Justin Forster', 'Ithaca College', 17),
('Cam Mayle', 'John Carroll University', 31),
('Pat Tatom', 'John Carroll University', 31),
('Clemente Sosa', 'John Jay College of Criminal Justice', 7),
('Jake Lieberman', 'John Jay College of Criminal Justice', 7),
('Gabriel Castellano', 'Johns Hopkins University', 6),
('Rob Saghy', 'Juniata College', 16),
('Tye Levy', 'Juniata College', 16),
('Tony Schimony', 'Juniata College', 16),
('Brenden Craig', 'Kalamazoo College', 20),
('J.P. McBride', 'Kalamazoo College', 20),
('Matt Rehfeldt', 'Kalamazoo College', 20),
('Ryan Beadle', 'Kalamazoo College', 20),
('Ken Beelen', 'Kalamazoo College', 20),
('Steve Bucchignano', 'Kean University', 26),
('Gary Galvach', 'Kean University', 26),
('Michael Matera', 'Kean University', 26),
('Dave Vargo', 'Kean University', 26),
('Sal Taormina', 'Kean University', 26),
('Tim Lunn', 'Keene State College', 18),
('John Luopa', 'Keene State College', 18),
('Connor Longley', 'Keene State College', 18),
('Noah Plantamuro', 'Keene State College', 18),
('Shaun McKenna', 'Keene State College', 18),
('Jared Ferenchak', 'Kenyon College', 28),
('Ronnie Krsolovic', 'Kenyon College', 28),
('Curtis Shultz', 'Keuka College', 13),
('Jamie Shevchik ''07', 'Keystone College', 42),
('Brian Del Rosso ''12', 'Keystone College', 42),
('Johnny McGarvey', 'Keystone College', 42),
('Ace Brogna', 'Keystone College', 42),
('Gary Ruby', 'Keystone College', 42),
('Robert Gouldsbury', 'Keystone College', 42),
('Rocco DePietro ''22', 'Keystone College', 42),
('Jordan Art ''23', 'Keystone College', 42),
('JARED SMIGELSKI', 'King s College (Pennsylvania)', 21),
('MIKE ZAPOTOSKI', 'King s College (Pennsylvania)', 21),
('RYAN WHETSTONE', 'King s College (Pennsylvania)', 21),
('MATT BOUND', 'King s College (Pennsylvania)', 21),
('NICK ZAROLA', 'King s College (Pennsylvania)', 21),
('Nick Milligan', 'Knox College', 22),
('Hunter Treece', 'La Roche University', 2),
('Justin Jurek', 'Lakeland University', 29),
('Tyler Cunningham', 'Lancaster Bible College', 42),
('Colin Brubaker', 'Lancaster Bible College', 42),
('Zach Clemens', 'Lancaster Bible College', 42),
('Matt Sammarco', 'Lasell University', 14),
('Jack Snyder', 'Lasell University', 14),
('Justin Banks', 'Lasell University', 14),
('Trent Whitcomb', 'Lawrence University', 22),
('AJ Verhage', 'Lawrence University', 22),
('Chase Kersten', 'Lawrence University', 22),
('Tom Wilson', 'Lawrence University', 22),
('Beth Woerner', 'Lebanon Valley College', 21),
('Chad Schell', 'Lebanon Valley College', 21),
('Zach Haas', 'Lebanon Valley College', 21),
('Jared Boger', 'Lebanon Valley College', 21),
('Robert Nordall ''05', 'Lebanon Valley College', 21),
('Andrew Miles', 'Lebanon Valley College', 21),
('Nilson Ibert', 'Lehman College', 7),
('Ross Skipper', 'LeTourneau University', 4),
('Brandt Wood', 'LeTourneau University', 4),
('Rob Vance', 'Lewis & Clark College', 30),
('Bill Allen', 'Lewis & Clark College', 30),
('Kyle McCormick', 'Lewis & Clark College', 30),
('Carl Johnson', 'Linfield University', 30),
('Larry Carlson', 'Linfield University', 30),
('Braden Wells', 'Linfield University', 30),
('Aidan Wojciehowski', 'Loras College', 3),
('Don Pirkle', 'Loras College', 3),
('Nolan Weber', 'Loras College', 3),
('Travis Pelton', 'Loras College', 3),
('Travis Olson', 'Loras College', 3),
('Dylan Pardoe', 'Loras College', 3),
('Dom Gentile', 'Loras College', 3),
('Colin Lacey', 'Luther College', 3),
('Noah Herried', 'Luther College', 3),
('Zac Cronk', 'Lycoming College', 21),
('Dustin Johnson', 'Lycoming College', 21),
('Jim Dinsmore', 'Lycoming College', 21),
('Evan Evans', 'Lycoming College', 21),
('Nick Worcester', 'Macalester College', 23),
('Graig Weber', 'Macalester College', 23),
('Jamie Eggleston', 'Macalester College', 23),
('Joe Shallenberger', 'Macalester College', 23),
('Mike Davis', 'Macalester College', 23),
('Chris Peterson', 'Macalester College', 23),
('Andy Johnson', 'Macalester College', 23),
('Chris Bessey', 'University of Maine, Farmington', 27),
('Kyle Baker', 'Manchester University', 15),
('Josh Brock', 'Manchester University', 15),
('Daniel Owens', 'Manhattanville College', 34),
('Chris Nardozzi', 'Manhattanville College', 34),
('Caleb Dohms', 'Marian University (Wisconsin)', 29),
('Chris Tekulve', 'Marietta College', 31),
('Mike Mulvey', 'Marietta College', 31),
('Evan Brockmeier', 'Marietta College', 31),
('Bill Mosca', 'Marietta College', 31),
('Edgar Arango', 'State University of New York Maritime College', 34),
('Randy Cox', 'Martin Luther College', 44),
('Troy Kamm', 'Martin Luther College', 44),
('Mitch Wilson', 'University of Mary Hardin-Baylor', 4),
('Todd Haney', 'University of Mary Hardin-Baylor', 4),
('Malek Bolin', 'University of Mary Hardin-Baylor', 4),
('Cooper Hake', 'University of Mary Hardin-Baylor', 4),
('Hunter Jones', 'University of Mary Hardin-Baylor', 4),
('Tommy Murphy', 'University of Mary Washington', 8),
('Adam Dofflemyer', 'University of Mary Washington', 8),
('Shane Halley', 'Marymount University (Virginia)', 5),
('Sam Bender', 'Marymount University (Virginia)', 5),
('Daniel Raley', 'Marymount University (Virginia)', 5),
('Conner Hall', 'Marymount University (Virginia)', 5),
('Tyler Womer', 'Marymount University (Virginia)', 5),
('Brett Kelley', 'Marymount University (Virginia)', 5),
('Rocky Mauriello', 'Maryville College (Tennessee)', 10),
('Drew Henry', 'Maryville College (Tennessee)', 10),
('Jimmy Reese', 'Maryville College (Tennessee)', 10),
('Joe Diskin', 'Marywood University', 5),
('Rick Clifford', 'Marywood University', 5),
('Justin Haddix', 'Marywood University', 5),
('Morgan Theobald', 'Marywood University', 5),
('Brad Fogel', 'University of Massachusetts Boston', 18),
('Jacqui Reynolds', 'University of Massachusetts Boston', 18),
('Corey Allard', 'University of Massachusetts Boston', 18),
('Nick Lepore', 'University of Massachusetts Boston', 18),
('Ryan Westmoreland', 'University of Massachusetts, Dartmouth', 18),
('Rian McCarthy', 'University of Massachusetts, Dartmouth', 18),
('Mike Pratt', 'University of Massachusetts, Dartmouth', 18),
('Chris Ursillo', 'University of Massachusetts, Dartmouth', 18),
('Trey Martinez', 'McDaniel College', 6),
('Brian Culley', 'McDaniel College', 6),
('Boardman Adams', 'McMurry University', 4),
('Dirk Saltzgaber', 'McMurry University', 4),
('Matt Bur', 'Messiah University', 21),
('Joseph Saufley', 'Messiah University', 21),
('Joey Nieves-Markee', 'Messiah University', 21),
('Reed Wagner', 'Messiah University', 21),
('Jason Johnson', 'Messiah University', 21),
('Josh Monturo', 'Messiah University', 21),
('Sam Zercher', 'Messiah University', 21),
('Spencer Martin', 'Methodist University', 41),
('Eric Sibrizzi', 'Methodist University', 41),
('Mike Phelps', 'Middlebury College', 24),
('Henry Strmecki', 'Middlebury College', 24),
('Freddie Mosier', 'Middlebury College', 24),
('Dylan Hamilton', 'Millikin University', 9),
('Nathan Bonter', 'Millikin University', 9),
('Kevin Koslofski', 'Millikin University', 9),
('Luke Azzarelli', 'Millikin University', 9),
('Garrett Fritz', 'Millikin University', 9),
('Doug Fortenberry', 'Millsaps College', 35),
('Jackson Hailey', 'Millsaps College', 35),
('Chris Hart', 'Millsaps College', 35),
('Brandon Miller', 'Milwaukee School of Engineering', 29),
('Sean Meyer', 'Milwaukee School of Engineering', 29),
('Mason LeBreck', 'Milwaukee School of Engineering', 29),
('Justin Bickman', 'Milwaukee School of Engineering', 29),
('Harrison Ballantyne', 'University of Minnesota, Morris', 44),
('Mason Rapp', 'University of Minnesota, Morris', 44),
('Garrett deMarrais', 'Misericordia University', 21),
('Steve Homza', 'Misericordia University', 21),
('Bill Gregory', 'Misericordia University', 21),
('Danny Santos', 'Mitchell College', 14),
('Josh Tower', 'Mitchell College', 14),
('Ryan Jemar', 'Monmouth College (Illinois)', 22),
('Ron Nelson ''78', 'Monmouth College (Illinois)', 22),
('John Wells', 'Montclair State University', 26),
('Joe Norton', 'Montclair State University', 26),
('Jake Carr', 'Moravian University', 16),
('Evan Kulig', 'Moravian University', 16),
('Patrick Gully', 'Mount Aloysius College', 2),
('Frank Montecalvo', 'Mount Aloysius College', 2),
('Kyle Kittle', 'Mount St. Joseph University', 15),
('Jason Kammer', 'Mount St. Joseph University', 15),
('Jason Miller', 'Mount St. Joseph University', 15),
('Nelson Santiago', 'College of Mount Saint Vincent', 34),
('Rich Anderson', 'Mount Saint Mary College (New York)', 34),
('Paul Hesse', 'University of Mount Union', 31),
('Cory Douglass', 'University of Mount Union', 31),
('Evan Knott', 'University of Mount Union', 31),
('John Ventura', 'University of Mount Union', 31),
('Roy Jacobs', 'University of Mount Union', 31),
('Billy Goodal', 'University of Mount Union', 31),
('Pete Violante', 'Muhlenberg College', 6),
('Bryan Reagle', 'Muhlenberg College', 6),
('Michael Jacob', 'Muskingum University', 31),
('Tate Engle', 'Muskingum University', 31),
('Mark Rider', 'Muskingum University', 31),
('Dan Linsner', 'Nebraska Wesleyan University', 3),
('Mason Bennett', 'Nebraska Wesleyan University', 3),
('David Alvarez', 'Neumann University', 5),
('Andy Salzmann', 'Neumann University', 5),
('Ryan Gendron', 'New England College', 14),
('Nick Asselin', 'New England College', 14),
('Nick Cesare', 'New Jersey City University', 26),
('Raj Subramanian', 'New Jersey City University', 26),
('John McAndrew', 'New Jersey City University', 26),
('Sean Gibney', 'New Jersey City University', 26),
('Paul Tannucilli', 'New Jersey City University', 26),
('Frank Shipman', 'New Jersey City University', 26),
('Tommy McCarthy', 'The College of New Jersey', 26),
('Ed Yaris', 'The College of New Jersey', 26),
('Jason Leta', 'The College of New Jersey', 26),
('Brandon Rivera', 'State University of New York at New Paltz', 39),
('Tommy Cardona', 'New York University', 43),
('Frank Delgado', 'New York University', 43),
('Eddie Medina', 'New York University', 43),
('Ben Farber', 'New York University', 43),
('Tim Mayo', 'Nichols College', 11),
('Jose Martinez', 'Nichols College', 11),
('Brad Ellis', 'Nichols College', 11),
('Bard Collins', 'North Carolina Wesleyan University', 41),
('Connor Christman', 'North Central College', 9),
('Tim Stoddard', 'North Central College', 9),
('Tim Peraino', 'North Central College', 9),
('Joe Keenan', 'North Central College', 9),
('Tom Errico', 'North Central College', 9),
('Mike Duckhorn', 'North Central College', 9),
('Brian White', 'North Central College', 9),
('Jeremy Busch', 'North Central College', 9),
('Cameron Allen', 'North Central College', 9),
('Matt Farland', 'North Central University', 44),
('Adam Hill', 'North Central University', 44),
('Matt Ozanic', 'North Park University', 9),
('Dan Kusinski', 'North Park University', 9),
('Kenny Laveau', 'North Park University', 9),
('Sam Matthews', 'Vermont State University Lyndon', 27),
('Nate Stewart', 'Vermont State University Lyndon', 27),
('Nick Rackley', 'Northland College', 44),
('Nick Podgornik', 'Northland College', 44),
('Seth Hackbarth', 'Northland College', 44),
('Shane Buckley', 'Northland College', 44),
('Gabe Eikum', 'University of Northwestern-St. Paul', 44),
('Tyler Sage', 'University of Northwestern-St. Paul', 44),
('Luke Widbin', 'University of Northwestern-St. Paul', 44),
('Keegan Vercoe', 'University of Northwestern-St. Paul', 44),
('Max Barthel', 'University of Northwestern-St. Paul', 44),
('Jake Preston', 'Norwich University', 14),
('Ben Woessner', 'Norwich University', 14),
('Tyler Schuch', 'Oberlin College', 28),
('Mike McClure', 'Oberlin College', 28),
('Eric Urban', 'Oberlin College', 28),
('Aaron Milam', 'Occidental College', 36),
('Carpenter Pagett', 'Occidental College', 36),
('Andy Hoyer', 'Oglethorpe University', 35),
(' ', 'Ohio Northern University', 31),
('Tyler Miller', 'Ohio Wesleyan University', 28),
('Mason Davis', 'Ohio Wesleyan University', 28),
('Dave Koblentz', 'Ohio Wesleyan University', 28),
('Brandon Szink', 'Ohio Wesleyan University', 28),
('Patrick Shortt', 'State University of New York at Old Westbury', 34),
('Rich Pecoraro', 'State University of New York at Old Westbury', 34),
('Lou Orologio', 'State University of New York at Old Westbury', 34),
('Mike Manetta', 'State University of New York at Old Westbury', 34),
('Dalton Beatty', 'State University of New York at Oneonta', 39),
('Colton Beatty', 'State University of New York at Oneonta', 39),
('Tyler Baker', 'State University of New York at Oswego', 39),
('Jason Heindorf', 'State University of New York at Oswego', 39),
('Robert Donnelly', 'State University of New York at Oswego', 39),
('Colton Hann', 'Otterbein University', 31),
('Tom Ryan', 'Otterbein University', 31),
('Lucas DiLuca', 'Otterbein University', 31),
('Russ Meade', 'Otterbein University', 31),
('Jackson Peloquin', 'Otterbein University', 31),
('Scott Richards', 'Pacific Lutheran University', 30),
('Landon Packard', 'Pacific Lutheran University', 30),
('Nate Packard', 'Pacific Lutheran University', 30),
('Aaron Svarthumle', 'Pacific University (Oregon)', 30),
('Mitch Thomas', 'Pacific University (Oregon)', 30),
('Brad Altomare', 'Pacific University (Oregon)', 30),
('Ryan Krout', 'Pacific University (Oregon)', 30),
('Heath Heller', 'Pennsylvania College of Technology', 42),
('Drae Lewis', 'Pennsylvania College of Technology', 42),
('Jake Deitz', 'Pennsylvania State Univ. Erie, the Behrend College', 2),
('Jason Bartlett', 'Pennsylvania State Univ. Erie, the Behrend College', 2),
('Ryan Smith', 'Pennsylvania State Univ. Erie, the Behrend College', 2),
('Marc Burchanowski', 'Pennsylvania State Univ. Erie, the Behrend College', 2),
('Billy Davis', 'Penn State Harrisburg', 42),
('Bill Sassaman', 'Penn State Harrisburg', 42),
('Dennis Bailey', 'Penn State Harrisburg', 42),
('John Cleary', 'Penn State Harrisburg', 42),
('Javier Garcia', 'Penn State Berks College', 42),
('Jim Bergeman', 'Penn State Berks College', 42),
('Mike Roth', 'Penn State University, Abington', 42),
('Jake Drossner', 'Penn State University, Abington', 42),
('Billy Manley', 'Pfeiffer University', 41),
('Trey Pearce', 'Piedmont University', 10),
('Jake McNabb', 'University of Pittsburgh, Bradford', 2),
('Jeff McWilliams', 'University of Pittsburgh, Greensburg', 2),
('Zack Zimmerman', 'University of Pittsburgh, Greensburg', 2),
('Jeff Pluta', 'Plattsburgh State University of New York', 39),
('Andrew Kramer', 'Plattsburgh State University of New York', 39),
('Eric Duquette', 'Plymouth State University', 18),
('Ben Hicks', 'Plymouth State University', 18),
('Dennis McManus', 'Plymouth State University', 18),
('Sean Thompson', 'Plymouth State University', 18),
('Peter Ludden', 'State University of New York Polytechnic Institute', 27),
('Tyler Schoff', 'State University of New York Polytechnic Institute', 27),
('Seve Kowalski', 'State University of New York Polytechnic Institute', 27),
('Michael Surina', 'Pomona-Pitzer Colleges', 36),
('Jason Staub', 'Pomona-Pitzer Colleges', 36),
('Anthony Lim', 'Pomona-Pitzer Colleges', 36),
('Thomas Thongmee', 'Pomona-Pitzer Colleges', 36),
('Jim Eissler', 'Principia College', 38),
('Bob Walz', 'University of Puget Sound', 30),
('AJ Morioka', 'University of Puget Sound', 30),
('Michael Johnson', 'University of Puget Sound', 30),
('Mark Jurczak', 'Purchase College, State University of New York', 34),
('JR Causa', 'Purchase College, State University of New York', 34),
('Lucas Vaz ''14', 'Purchase College, State University of New York', 34),
('Jacob Selden', 'Randolph-Macon College', 32),
('Charlie Fletcher', 'Randolph-Macon College', 32),
('Chris Hernandez', 'University of Redlands', 36),
('Steve Hernandez', 'University of Redlands', 36),
('Nick Theodorou', 'University of Redlands', 36),
('Josh Banuelos', 'University of Redlands', 36),
('Cameron Kundig', 'University of Redlands', 36),
('Chris Mahoney', 'Rensselaer Polytechnic Institute', 17),
('Cody Vincent ''12', 'Rensselaer Polytechnic Institute', 17),
('Thomas Neuman', 'Rensselaer Polytechnic Institute', 17),
('Jeff Cleanthes', 'Rhodes College', 35),
('Rudy Martin', 'Rhodes College', 35),
('Mikey Natze', 'Rhodes College', 35),
('Derek Loomans', 'Ripon College', 22),
('Alex Lopez', 'Ripon College', 22),
('Brice Swick', 'Ripon College', 22),
('Jeffrey Halter', 'Ripon College', 22),
('Jake Cedar', 'Ripon College', 22),
('Justin Johnson', 'University of Rochester', 43),
('Conner Lorenzo', 'University of Rochester', 43),
('Jake Shattuck', 'University of Rochester', 43),
('Michael Gibson', 'University of Rochester', 43),
('Tyler Leichtenberger', 'Rochester Institute of Technology', 17),
('Ben Terzini', 'Rochester Institute of Technology', 17),
('Justin Hallberg', 'Rockford University', 29),
('Dennis Kehrer', 'Rockford University', 29),
('Jim Hawrysko', 'Rockford University', 29),
('Marty Miller', 'Rockford University', 29),
('Tim Gelzinis', 'Roger Williams University', 11),
('Matt Rienzi', 'Roger Williams University', 11),
('Austin Nappi', 'Roger Williams University', 11),
('Ryan Kaveney', 'Rose-Hulman Institute of Technology', 15),
('Nathan Bonter', 'Rose-Hulman Institute of Technology', 15),
('James Martin', 'Rosemont College', 42),
('Glen Goldberg', 'Rosemont College', 42),
('Jake Stoller', 'Rosemont College', 42),
('Adam McKinlay', 'Rosemont College', 42),
('Joe Tremoglie', 'Rosemont College', 42),
('Mike Dickson', 'Rowan University', 26),
('Jordan Friedman', 'Rowan University', 26),
('Andrew Cartier', 'Rowan University', 26),
('Chris Rollins', 'Rowan University', 26),
('Nick Pontari', 'Russell Sage College', 13),
('Karl Steffen', 'Russell Sage College', 13),
('Ryan Parker', 'Russell Sage College', 13),
('Justin Brock', 'Russell Sage College', 13),
('Michael Branche', 'Russell Sage College', 13),
('Cameron Anderson', 'Russell Sage College', 13),
('Justin Pangburn', 'Russell Sage College', 13),
('Patrick Fisher', 'Rutgers, The State Univ. of New Jersey, Camden', 26),
('John Merkh', 'Rutgers, The State Univ. of New Jersey, Camden', 26),
('Derek Smolinski', 'Rutgers, The State Univ. of New Jersey, Camden', 26),
('Andrew Young', 'Rutgers, The State Univ. of New Jersey, Camden', 26),
('Bill Calhoun', 'Rutgers, The State Univ. of New Jersey, Camden', 26),
('R.J. McGettigan', 'Rutgers, The State Univ. of New Jersey, Camden', 26),
('Christian Scafidi', 'Rutgers, The State Univ. of New Jersey, Camden', 26),
('Marquay Mayo', 'Rutgers, The State Univ. of New Jersey, Newark', 26),
('Eric Reardon', 'Rutgers, The State Univ. of New Jersey, Newark', 26),
('Josh Miller', 'Rutgers, The State Univ. of New Jersey, Newark', 26),
('Ray Orta', 'Saint Elizabeth University', 42),
('Dan Sacco', 'Saint Elizabeth University', 42),
('Jared Coffey', 'Saint Elizabeth University', 42),
('Austin Heenan', 'Salisbury University', 8),
('Nicholas Palacios', 'Schreiner University', 37),
('Devin Hooper', 'Schreiner University', 37),
('Corvin Scott', 'University of the South', 35),
('Tyler Sherman', 'University of the South', 35),
('Kevin Anderson', 'Shenandoah University', 32),
('Chris Jenkins', 'Shenandoah University', 32),
('Nick Sborz ''06', 'Shenandoah University', 32),
('Jonathan Kaiser', 'Skidmore College', 17),
('J.T. Tellstone', 'Skidmore College', 17),
('John Barnes', 'Skidmore College', 17),
('Ed Boyce', 'University of Southern Maine', 18),
('Rod Choroszy', 'University of Southern Maine', 18),
('Shaun McKenna', 'University of Southern Maine', 18),
('Josh Stowell', 'University of Southern Maine', 18),
('Sam Dexter', 'University of Southern Maine', 18),
('Tim Downing', 'University of Southern Maine', 18),
('Tom Bennett', 'Southern Virginia University', 41),
('David Smith', 'Southern Virginia University', 41),
('Mike Montgomery', 'Southwestern University (Texas)', 37),
('Micah Saltzberg', 'Spalding University', 38),
('Dave Roth', 'St. John Fisher University', 13),
('Mike Cerame', 'St. John Fisher University', 13),
('Haralambos Papalouizos', 'St. John Fisher University', 13),
('Michael Beimel', 'St. John Fisher University', 13),
('Jason Spohn', 'Saint John s University (Minnesota)', 23),
('Scott Lieser', 'Saint John s University (Minnesota)', 23),
('Eamonn Andre', 'St. Lawrence University', 17),
('Trevon Van Egtern', 'Saint Mary s University of Minnesota', 23),
('Justin Kronebusch', 'Saint Mary s University of Minnesota', 23),
('Joseph Bryner ''21', 'St. Mary s College of Maryland', 42),
('Derek Taitano ''20', 'St. Mary s College of Maryland', 42),
('Andrew Collins ''21', 'St. Mary s College of Maryland', 42),
('Mike Wallerich', 'St. Norbert College', 29),
('Ethan Bemowski', 'St. Norbert College', 29),
('Jack Maastricht', 'St. Norbert College', 29),
('Connor Yakel', 'St. Norbert College', 29),
('Pete Maus', 'St. Olaf College', 23),
('Tony Mathison', 'St. Olaf College', 23),
('Seth Betts', 'The College of St. Scholastica', 23),
('Tim Anderson', 'The College of St. Scholastica', 23),
('Jake Lewis', 'The College of St. Scholastica', 23),
('Tanner Vavra', 'University of St. Thomas (Minnesota)', 40),
('Trey Vavra', 'University of St. Thomas (Minnesota)', 40),
('Greg Nesbitt', 'University of St. Thomas (Minnesota)', 40),
('Eden Cranston', 'University of St. Thomas (Minnesota)', 40),
('Derrick Snell', 'University of St. Thomas (Minnesota)', 40),
('Brendan Smith', 'Stevens Institute of Technology', 21),
('Ross Bartziokas', 'Stevens Institute of Technology', 21),
('Jayson Yano', 'Stevens Institute of Technology', 21),
('Paul Sotiropoulos', 'Stevens Institute of Technology', 21),
('Steve Bucci', 'Stockton University', 26),
('Glenn Wyatt', 'Stockton University', 26),
('Steve Struble', 'Stockton University', 26);


ALTER TABLE Review ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;



CREATE VIEW CoachWithDivision AS

SELECT c.name AS coach_name, c.team, conf.name AS conference_name, d.name AS division_name
FROM Coach c
JOIN Conference conf ON c.con_ID = conf.con_ID
JOIN Division d ON conf.div_ID = d.div_ID;

SELECT * FROM CoachWithDivision;
